### ISSUE TITLE
Error in bot.py line 120

### ISSUE THREAD

**Issue by aleff-github** [Andromeda606/TikTok-AccountCreator#1]
Hi i have this error on console
`Traceback (most recent call last):
  File "tiktok.py", line 2, in <module>
    import bot
  File "/home/nonameon/Documents/TikTok-AccountCreator-main/bot.py", line 120, in <module>
    'javascript:document.getElementsByClassName("select-container-36J-Y")[0].click();document.getElementsByClassName("list-item-26TR9")[0].click();document.getElementsByClassName("select-container-36J-Y")[1].click();document.getElementsByClassName("list-item-26TR9")[1].click();document.getElementsByClassName("select-container-36J-Y")[2].click();document.getElementsByClassName("list-item-26TR9")[40].click();document.getElementsByClassName("login-button-Rt4Hk")[0].click();')
  File "/home/nonameon/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/nonameon/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/nonameon/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unsupported protocol
  (Session info: chrome=87.0.4280.66)
`

How can i solve?

**Comment by Andromeda606** [comment]
Upgrade your selenium web driver .It is compatiblity issues with webdriver and your browser version. I updated my pom file with latest version of chrome web driver and it worked. Upgrading the chrome web driver Version to 3.9.1 and above also resolves the issue.

**Comment by Andromeda606** [comment]
can you try again? The code has been updated.

**Comment by aleff-github** [comment]
Hi, i tried again now and i have this error 
`Traceback (most recent call last):
  File "bot.py", line 119, in <module>
    browser.find_element_by_xpath("/html/body/div[1]/div/div[1]/form/div[2]/div[1]/div").click()
  File "/home/nonameon/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/nonameon/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/nonameon/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/nonameon/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <div class="select-container-2Ubyt not-selected-1Tb33"> is not clickable at point (477,263) because another element <div class="container-3MEuw"> obscures it`

Don't you have it? 

[Error image](https://i.ibb.co/nwk1ckJ/errore.png)

**Comment by Andromeda606** [comment]
![image](https://user-images.githubusercontent.com/43077625/104090213-2c76a380-5286-11eb-98d2-67312aa81d20.png)
Can you assign the innerHTML code from the "date-selector-pc-oyWlO" line of tiktok? I do not have this error.

**Comment by aleff-github** [comment]
This is my situation: https://ibb.co/QcnW1xw

The problem can be that i have gekodriver in italian and not in english?

**Edit:** Ok yes this error is fixed using eng language, but now the program is going in loop printing just "getMail"
Error image: https://ibb.co/qYpN2J9

**Comment by Andromeda606** [comment]
The getMail script should query whether the code from gmaild exists. In short, if the code has been sent, it is waiting to be entered after receiving that code and therefore it is constantly waiting for the code to arrive. Probably there was a problem in requesting code, I wrote this bot back in the past, I don't know if it works too much now, but I have no doubt that it can be improved

**Comment by aleff-github** [comment]
You must change 127 line with something like `browser.find_element_by_xpath("/html/body/div[1]/div/div[1]/form/div[2]/div[3]/ul/li[29]").click()` because if you don't do that you will choose 2017 and it isn't good for TikTok.

An another thing is that you didn't write a code where you will click on "Send code" button so you must add it `browser.find_element_by_xpath("/html/body/div[1]/div/div[1]/form/div[4]/div[5]/button").click()` at 129 code line... before getGmail()

However i don't think that it is utilizable because i tried now and i have an error like "You can't use this email because visit tiktok too much frequently, so i think that TikTok inserted a control because without gekodriver or chromedriver i can use this email...
